### ISSUE TITLE
Command 'hostname -I' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by tsan1** [smartsenselab/sensecam-discovery#1]
Hi, 

I am getting this error . Could you please help. What does it mean?

Br,
Titir

**Comment by ricardobf** [comment]
Hi, 

Are you using linux distro?

**Comment by tsan1** [comment]
Hi, 
I am using in Windows 10, but I installed the package through pip install sensecam-discovery. Does it not support windows?

**Comment by ricardobf** [comment]
Unfortunately not, last time I checked there wasn't the "netifaces" extension for Windows.
But you can use MobaXterm and its Network Scan tool.

**Comment by ricardobf** [comment]
Now it works on Windows. =]

**Comment by builder555** [comment]
same error is happening on a mac
